# Usar imagem base do Node.js
FROM node:18

# Definir diretório de trabalho
WORKDIR /app

# Copiar package.json e instalar dependências
COPY package*.json ./

RUN npm install

# Copiar o restante dos arquivos do frontend
COPY . .

# Buildar o projeto (gerar arquivos prontos para produção)
RUN npm run build

# Instalar servidor web leve para servir o build
RUN npm install -g serve

# Expor a porta do frontend (serve padrão é 3000)
EXPOSE 3000

# Comando final para rodar o frontend
CMD ["serve", "-s", "dist", "-l", "3000"]
