# Usar imagem base do Node.js
FROM node:18

# Definir diretório de trabalho
WORKDIR /app

# Copiar package.json e package-lock.json
COPY package*.json ./

# Instalar dependências
RUN npm install

# Copiar todos os arquivos do projeto
COPY . .

# Expor a porta que o backend usa
EXPOSE 3001

# Comando para rodar a aplicação
CMD ["npm", "start"]
